version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: bookshop_frontend
    ports:
      - 8030:3000
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend

  backend:
    build: ./backend
    container_name: bookshop_backend
    ports:
      - 5123:5123
    restart: always
    env_file:
      - .env


  database:
    image: mongo:latest
    container_name: bookshop_database
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./database/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
